create extension if not exists "pgcrypto";

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  user_id uuid not null references auth.users(id) on delete cascade,
  company text not null,
  role text not null,
  website text,
  logoUrl text,
  dateApplied date not null,
  status text not null default 'Applied',
  notes text
);

alter table public.applications
  add constraint applications_status_check
  check (status in ('Applied', 'Interview', 'Offer', 'Rejected'));

alter table public.applications
  add constraint applications_company_length_check
  check (char_length(trim(company)) between 2 and 50);

alter table public.applications
  add constraint applications_role_length_check
  check (char_length(trim(role)) between 2 and 80);

alter table public.applications
  add constraint applications_notes_length_check
  check (notes is null or char_length(notes) <= 500);

create index if not exists applications_user_id_idx
  on public.applications (user_id);

create index if not exists applications_created_at_idx
  on public.applications (created_at desc);

alter table public.applications enable row level security;

drop policy if exists "Users can view their own applications" on public.applications;
drop policy if exists "Users can insert their own applications" on public.applications;
drop policy if exists "Users can update their own applications" on public.applications;
drop policy if exists "Users can delete their own applications" on public.applications;

create policy "Users can view their own applications"
on public.applications
for select
using (auth.uid() = user_id);

create policy "Users can insert their own applications"
on public.applications
for insert
with check (auth.uid() = user_id);

create policy "Users can update their own applications"
on public.applications
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own applications"
on public.applications
for delete
using (auth.uid() = user_id);
